### PR TITLE
Support RSA-SHA256, support certificate chains, minor fixes

### PR DESCRIPTION
**Pull request by petrohi**

### CODE REVIEW

**Comment by arekinath** [comment]
Looks good other than two minor things -- see my inline comments. The travis-ci build failing is because rebar.config still says cowboy HEAD -- I've just pushed a patch to my master to make it look at the 1.0.x branch instead.

**Comment by petrohi** [comment]
Your suggested changes look good to me. I won't be able to make them immediately--pretty stumped with new product launch. If you wish you can go ahead and make them. I will then integrate your changes in our fork.

**Comment by arekinath** [comment]
All done, thanks for your work. :)

I added sha256 fingerprint support, too, so you can supply things like `{sha256, <<Hash>>}` in the `Fingerprints` argument to `xmerl_dsig:verify/2`. When you're giving these to `esaml_sp`, you use the newer style fingerprint format like `"SHA256:iNQmb9TmM40TuEX88olXnSCciXgjuSF9o+Fhk28DFYk="` (base64 encoded). Old hex-encoded fingerprints are always assumed to be SHA1.

**Comment by petrohi** [comment]
Awesome! Thanks!

**Pull request merged**
